server:
  port: 8082

spring:
  mail:
    host: smtp.163.com
    username: 13286261813@163.com
    password: ARqCB3BRskdjDqvk


  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /

    redis:
      host: localhost
      port: 6379
      password:


  security:
    jwt:
      key: juzic # 密钥
      expire: 7 # 过期时间

  datasource:

    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
